##' A transcriptome data matrix. The data is composed of 520 significant DEGs 
##' (differentially expressed genes) and 898 transcription factors generated 
##' by Bottje et al. (2017).
##'
##' Twelve RNA-seq libraries were produced using breast muscle RNA samples 
##' from 6 HFE (high food efficiency) and 6 LFE (low FE) broilers. This 
##' chicken RNA-seq data were generated by mapping the reads to Gallus gallus
##' genome assembly version 4.
##'
##' @name ToniData
##' @docType data
##' @title An example transcriptome dataset by Bottje et al. (2017)
##'
##' @keywords datasets
##' @references Bottje et al. BMC Syst Biol 11:29 (2017)
##' @author Atsushi Fukushima
NULL

##' A list of differentially expressed genes (DEGs) based on Chicken RNA-seq 
##' generated by Bottje et al. (2017).
##'
##' The number of DEGs here is 520.
##'
##' @name ToniData.DEGs
##' @docType data
##' @title A list of DEGs in chicken RNA-seq data.
##'
##' @keywords datasets
##' @references Bottje et al. BMC Syst Biol 11:29 (2017)
##' @author Atsushi Fukushima
NULL

##' A list of transcription factors (TFs) based on Chicken RNA-seq generated 
##' by Bottje et al. (2017).
##'
##' The number of TFs here is 898.
##'
##' @name ToniData.TFs
##' @docType data
##' @title A list of TFs in chicken RNA-seq data.
##'
##' @keywords datasets
##' @references Bottje et al. BMC Syst Biol 11:29 (2017)
##' @author Atsushi Fukushima
NULL
